version: 2
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cd tinder && ./mvnw install
      - run: cd tinderarchetype && ./mvnw package
      - save_cache:
          paths:
            - ~/.m2
          key: dependencies
workflows:
  version: 2
  build:
    jobs:
      - build