version: 2
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11
    steps:
      - checkout
      - setup_remote_docker
      - run: cd tinder && ./mvnw install
      - run: cd tinderarchetype && ./mvnw package