version: 2
jobs:
  buildlib:
    docker:
      - image: adoptopenjdk/openjdk11
    steps:
      - checkout
      - restore_cache:
          keys: [dependencies]
      - run: cd tinder && ./mvnw clean install deploy -P release --settings ossrh_settings.xml
      - save_cache:
          key: dependencies
          paths: [~/.m2]
  build:
    docker:
      - image: adoptopenjdk/openjdk11
    steps:
      - checkout
      - restore_cache:
          keys: [dependencies]
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cd tinderarchetype && ./mvnw package
      - save_cache:
          key: dependencies
          paths: [~/.m2]
      - persist_to_workspace:
          root: .
          paths:
            - tinderarchetype/target/*.jar
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo apt-get install awscli
      - run:
          name: Sign into AWS ecr
          command: $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - run:
          name: Push image
          command: |
            export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/tinder/tinderarchetype:master"
            docker build -t "${FULL_IMAGE_NAME}" --build-arg JAR_FILE=tinder-archetype-1.0-SNAPSHOT.jar tinderarchetype
            docker push ${FULL_IMAGE_NAME}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - buildlib:
          context: mvn_central
      - build:
          requires: [buildlib]
      - deploy:
          context: aws
          requires: [build]